### ISSUE TITLE
select all + run "model_nll" returning error

### ISSUE THREAD

**Issue by ncy-xing** [thelexiconlab/forager-web#4]
Overflows or invalid values in lines 192, 193, 198 of model_dynamic_phon() method in foraging.py:

<img width="1376" alt="Screenshot 2023-04-05 at 2 04 20 PM" src="https://user-images.githubusercontent.com/92757073/230166327-67d9b7f2-f776-4b80-a02a-c5eed941b104.png">

**Comment by ncy-xing** [comment]
**Runtime warnings on small dataset:** 
- File used: test-file.txt in test folder (data for 2 subjects)
- Selecting: switch=all, model=all 
- Running: Model and NLL results

Same runtime warnings halfway through:
/Users/nxing/Library/CloudStorage/OneDrive-Personal/Lexicon/deployment/forager-web/forager/foraging.py:184: RuntimeWarning: overflow encountered in scalar multiply...etc

Also repeatedly gave performance warning on run_foraging_web.py:450-454
```
nll_df['NLL_{model}'.format(model=model_names[k])] = result[4]
nll_df['Semantic_Similarity'] = output[4][0]
nll_df['Frequency_Value'] = output[4][2]
nll_df['Phonological_Similarity'] = output[4][4]
```


Warning message: 
/Users/nxing/Library/CloudStorage/OneDrive-Personal/Lexicon/deployment/forager-web/run_foraging_web.py:450: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

(Note to self: Selecting switch = all, running Model and nll results in general takes a long time, eg 2 subjects --> 13 sec)

**Comment by ncy-xing** [comment]
"RuntimeWarning: overflow encountered in scalar multiply" from passing in values too large for the data type

fragmented dataframes:
[https://stackoverflow.com/questions/68292862/performancewarning-dataframe-is-highly-fragmented-this-is-usually-the-result-o](url)

**Comment by abhilasha-kumar** [comment]
Do you still get the error if you only select and run `model_dynamic_phon()`? I'm wondering if this is a model-specific issue. Also, is there a way to continue to run by ignoring the warnings? the package itself does run despite the warnings right?

**Comment by ncy-xing** [comment]
Running only 'model_dynamic_phon()' by selecting pdynamic on the webpage results in the same runtime warnings. The package will continue running and return despite the warnings, but at a slow speed (e.g., 4 minutes for two subjects). I suppose this is not an issue locally, but on web.

Warning message (again):
/Users/nxing/Library/CloudStorage/OneDrive-Personal/Lexicon/deployment/forager-web/run_foraging_web.py:450: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
